name: battleship-tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./battleship
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name : install  project dependencies
        run: npm install --force

      - name: run tests
        run: npm test